"""
Django settings for scientistSite project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!di0ggq!p_kto1=og+fl3=joy-w-m&b(7&372der6^$ffx$3ec'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SITE_NAME = 'https://www.allday.rest'
ALLOWED_HOSTS = [SITE_NAME,'http://www.allday.rest','www.allday.rest','allday.rest','localhost','165.22.27.247','http://allday.rest','https://allday.rest']


CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = [
        'http://localhost',
        'http://165.22.27.247',
        'http://0.0.0.0:',
        'http://allday.rest',
        'http://www.allday.rest',
        'http://localhost',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'main',
    'api.apps.ApiConfig',
    'rest_framework',
    'django_filters',
    'chat',
    'channels',
    'corsheaders'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.ExpiringTokenAuthentication',
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'scientistSite.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scientistSite.wsgi.application'

ASGI_APPLICATION = 'scientistSite.routing.application'

CHANNEL_LAYERS = {
    'default':{
        'BACKEND':'channels_redis.core.RedisChannelLayer',
        'CONFIG':{
            'hosts': [('127.0.0.1','6379')]
        }
    }
}

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DB_NAME = "scientist_bd"
DB_USER = "django"
DB_PASSWORD = "adminlikeadmin"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

AUTH_USER_MODEL = 'main.scientist'

#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static_back"),
#    os.path.join(BASE_DIR, 'media_back'),
#]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media_back')
MEDIA_URL = '/media_back/'

STATIC_URL = '/static_back/'
STATIC_ROOT = os.path.join(BASE_DIR, "static_back")