# Generated by Django 3.0.8 on 2020-12-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='academicDegree',
            field=models.CharField(choices=[('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук')], default='', max_length=60, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='academicTitle',
            field=models.CharField(choices=[('Профессор', 'Профессор'), ('Доцент', 'Доцент')], default='', max_length=60, verbose_name='Ученое звание'),
        ),
    ]
