# Generated by Django 3.0.8 on 2020-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201203_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='academicDegree',
            field=models.CharField(choices=[('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук')], default='', max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='academicTitle',
            field=models.CharField(choices=[('Профессор', 'Профессор'), ('Доцент', 'Доцент')], default='', max_length=100, verbose_name='Ученое звание'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='codeSpeciality',
            field=models.CharField(choices=[('Коррекционная психология', 'Коррекционная психология'), ('Коррекционная педагогика', 'Коррекционная педагогика')], default='', max_length=100, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='image',
            field=models.ImageField(default='images/scientistPhoto/default.png', max_length=255, null=True, upload_to='images/scientistPhoto', verbose_name='Фотография пользователя'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='job_place',
            field=models.CharField(blank=True, default='Место работы', max_length=120, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='keyWords',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='keyWordsString',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Строка ключевых слов'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='mainResults',
            field=models.TextField(blank=True, default='', verbose_name='Основные результаты исследовательской деятельности'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='position',
            field=models.CharField(blank=True, default='Должность', max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='region',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Cубъект'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='surname',
            field=models.CharField(default='', max_length=60, verbose_name='Фамилия'),
        ),
    ]
