# Generated by Django 3.0.8 on 2020-12-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201209_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headLine',
            field=models.CharField(max_length=256, verbose_name='Название новости'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='academicDegree',
            field=models.CharField(blank=True, choices=[('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук')], default='', max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='academicTitle',
            field=models.CharField(blank=True, choices=[('Профессор', 'Профессор'), ('Доцент', 'Доцент')], default='', max_length=100, verbose_name='Ученое звание'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='codeSpeciality',
            field=models.CharField(blank=True, choices=[('Коррекционная психология', 'Коррекционная психология'), ('Коррекционная педагогика', 'Коррекционная педагогика')], default='', max_length=100, verbose_name='Специальность'),
        ),
    ]
