# Generated by Django 3.0.8 on 2020-12-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201209_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientist',
            old_name='phone_numer',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='scientist',
            name='job_place',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='position',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
