# Generated by Django 2.2.15 on 2020-12-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201209_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='dier_sovet',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Диссертационный совет'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='editorial_boards',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Редколлегия научных изданий'),
        ),
    ]
