# Generated by Django 3.1.4 on 2020-12-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201218_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='image',
            field=models.ImageField(default='media_back/images/scientistPhoto/default.png', max_length=255, null=True, upload_to='media_back/images/scientistPhoto', verbose_name='Фотография пользователя'),
        ),
    ]
