# Generated by Django 3.1.4 on 2020-12-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201223_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='image',
            field=models.ImageField(default='images/scientistPhoto/default.png', max_length=255, null=True, upload_to='images/scientistPhoto', verbose_name='Фотография пользователя'),
        ),
    ]
