# Generated by Django 3.1.4 on 2020-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201223_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=8192, verbose_name='Текст новости'),
        ),
    ]
